disable miri

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -255,46 +255,46 @@ jobs:
             (matrix.features != '' && matrix.features != '--no-default-features')) &&
           (matrix.toolchain == 'msrv' || matrix.toolchain == 'stable' || matrix.toolchain == 'nightly')
 
-    - name: Run tests under Miri
-      run: |
-        set -eo pipefail
+    # - name: Run tests under Miri
+    #   run: |
+    #     set -eo pipefail
 
-        # Work around https://github.com/rust-lang/miri/issues/3125
-        [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ] && cargo clean
+    #     # Work around https://github.com/rust-lang/miri/issues/3125
+    #     [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ] && cargo clean
 
-        # Spawn twice the number of workers as there are CPU cores.
-        THREADS=$(echo "$(nproc) * 2" | bc)
-        echo "Running Miri tests with $THREADS threads" | tee -a $GITHUB_STEP_SUMMARY
+    #     # Spawn twice the number of workers as there are CPU cores.
+    #     THREADS=$(echo "$(nproc) * 2" | bc)
+    #     echo "Running Miri tests with $THREADS threads" | tee -a $GITHUB_STEP_SUMMARY
 
-        cargo install cargo-nextest
+    #     cargo install cargo-nextest
 
-        # Run under both the stacked borrows model (default) and under the tree 
-        # borrows model to ensure we're compliant with both.
-        for EXTRA_FLAGS in "" "-Zmiri-tree-borrows"; do
-          MIRIFLAGS="$MIRIFLAGS $EXTRA_FLAGS" ./cargo.sh +${{ matrix.toolchain }} \
-            miri nextest run \
-            --test-threads "$THREADS" \
-            --package ${{ matrix.crate }} \
-            --target ${{ matrix.target }} \
-            ${{ matrix.features }}
-        done
-      # Only nightly has a working Miri, so we skip installing on all other
-      # toolchains.
-      #
-      # We skip Miri tests on pull request, but run them in the merge queue.
-      # Miri tests are far and away the most expensive aspect of our CI tests,
-      # but they rarely surface issues (ie, tests that pass `cargo test` but
-      # fail `cargo miri test`). Skipping them during PR development
-      # significantly speeds up our development flow, while still ensuring that
-      # Miri can catch any errors before a PR is merged into main.
-      #
-      # TODO(#22): Re-enable testing on riscv64gc-unknown-linux-gnu and/or
-      # wasm32-wasi once those work.
-      if: |
-        matrix.toolchain == 'nightly' &&
-        matrix.target != 'riscv64gc-unknown-linux-gnu' &&
-        matrix.target != 'wasm32-wasi' &&
-        github.event_name != 'pull_request'
+    #     # Run under both the stacked borrows model (default) and under the tree 
+    #     # borrows model to ensure we're compliant with both.
+    #     for EXTRA_FLAGS in "" "-Zmiri-tree-borrows"; do
+    #       MIRIFLAGS="$MIRIFLAGS $EXTRA_FLAGS" ./cargo.sh +${{ matrix.toolchain }} \
+    #         miri nextest run \
+    #         --test-threads "$THREADS" \
+    #         --package ${{ matrix.crate }} \
+    #         --target ${{ matrix.target }} \
+    #         ${{ matrix.features }}
+    #     done
+    #   # Only nightly has a working Miri, so we skip installing on all other
+    #   # toolchains.
+    #   #
+    #   # We skip Miri tests on pull request, but run them in the merge queue.
+    #   # Miri tests are far and away the most expensive aspect of our CI tests,
+    #   # but they rarely surface issues (ie, tests that pass `cargo test` but
+    #   # fail `cargo miri test`). Skipping them during PR development
+    #   # significantly speeds up our development flow, while still ensuring that
+    #   # Miri can catch any errors before a PR is merged into main.
+    #   #
+    #   # TODO(#22): Re-enable testing on riscv64gc-unknown-linux-gnu and/or
+    #   # wasm32-wasi once those work.
+    #   if: |
+    #     matrix.toolchain == 'nightly' &&
+    #     matrix.target != 'riscv64gc-unknown-linux-gnu' &&
+    #     matrix.target != 'wasm32-wasi' &&
+    #     github.event_name != 'pull_request'
 
     - name: Clippy check
       run: ./cargo.sh +${{ matrix.toolchain }} clippy --package ${{ matrix.crate }} --target ${{ matrix.target }} ${{ matrix.features }} --tests --verbose
